// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	cart "ecommerce/features/cart"

	mock "github.com/stretchr/testify/mock"
)

// CartService is an autogenerated mock type for the CartService type
type CartService struct {
	mock.Mock
}

// AddToCart provides a mock function with given fields: token, productID, addToCart
func (_m *CartService) AddToCart(token interface{}, productID uint, addToCart cart.Core) (cart.Core, error) {
	ret := _m.Called(token, productID, addToCart)

	var r0 cart.Core
	if rf, ok := ret.Get(0).(func(interface{}, uint, cart.Core) cart.Core); ok {
		r0 = rf(token, productID, addToCart)
	} else {
		r0 = ret.Get(0).(cart.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, uint, cart.Core) error); ok {
		r1 = rf(token, productID, addToCart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CartList provides a mock function with given fields: token
func (_m *CartService) CartList(token interface{}) ([]cart.Core, error) {
	ret := _m.Called(token)

	var r0 []cart.Core
	if rf, ok := ret.Get(0).(func(interface{}) []cart.Core); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cart.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CartResult provides a mock function with given fields: token
func (_m *CartService) CartResult(token interface{}) ([]cart.Core, error) {
	ret := _m.Called(token)

	var r0 []cart.Core
	if rf, ok := ret.Get(0).(func(interface{}) []cart.Core); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cart.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: token, cartID
func (_m *CartService) Delete(token interface{}, cartID uint) error {
	ret := _m.Called(token, cartID)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, uint) error); ok {
		r0 = rf(token, cartID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateQty provides a mock function with given fields: token, cartID, quantity
func (_m *CartService) UpdateQty(token interface{}, cartID uint, quantity int) (cart.Core, error) {
	ret := _m.Called(token, cartID, quantity)

	var r0 cart.Core
	if rf, ok := ret.Get(0).(func(interface{}, uint, int) cart.Core); ok {
		r0 = rf(token, cartID, quantity)
	} else {
		r0 = ret.Get(0).(cart.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, uint, int) error); ok {
		r1 = rf(token, cartID, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCartService interface {
	mock.TestingT
	Cleanup(func())
}

// NewCartService creates a new instance of CartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCartService(t mockConstructorTestingTNewCartService) *CartService {
	mock := &CartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
