// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"

	product "ecommerce/features/product"
)

// ProductService is an autogenerated mock type for the ProductService type
type ProductService struct {
	mock.Mock
}

// AddProduct provides a mock function with given fields: token, formHeader, newProduct
func (_m *ProductService) AddProduct(token interface{}, formHeader multipart.FileHeader, newProduct product.Core) (product.Core, error) {
	ret := _m.Called(token, formHeader, newProduct)

	var r0 product.Core
	if rf, ok := ret.Get(0).(func(interface{}, multipart.FileHeader, product.Core) product.Core); ok {
		r0 = rf(token, formHeader, newProduct)
	} else {
		r0 = ret.Get(0).(product.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, multipart.FileHeader, product.Core) error); ok {
		r1 = rf(token, formHeader, newProduct)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AllProduct provides a mock function with given fields:
func (_m *ProductService) AllProduct() ([]product.Core, error) {
	ret := _m.Called()

	var r0 []product.Core
	if rf, ok := ret.Get(0).(func() []product.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]product.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: token, productID
func (_m *ProductService) Delete(token interface{}, productID uint) error {
	ret := _m.Called(token, productID)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, uint) error); ok {
		r0 = rf(token, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EditProduct provides a mock function with given fields: token, formHeader, productID, editedProduct
func (_m *ProductService) EditProduct(token interface{}, formHeader multipart.FileHeader, productID uint, editedProduct product.Core) (product.Core, error) {
	ret := _m.Called(token, formHeader, productID, editedProduct)

	var r0 product.Core
	if rf, ok := ret.Get(0).(func(interface{}, multipart.FileHeader, uint, product.Core) product.Core); ok {
		r0 = rf(token, formHeader, productID, editedProduct)
	} else {
		r0 = ret.Get(0).(product.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, multipart.FileHeader, uint, product.Core) error); ok {
		r1 = rf(token, formHeader, productID, editedProduct)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductDetail provides a mock function with given fields: productID
func (_m *ProductService) ProductDetail(productID uint) (product.Core, error) {
	ret := _m.Called(productID)

	var r0 product.Core
	if rf, ok := ret.Get(0).(func(uint) product.Core); ok {
		r0 = rf(productID)
	} else {
		r0 = ret.Get(0).(product.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewProductService interface {
	mock.TestingT
	Cleanup(func())
}

// NewProductService creates a new instance of ProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProductService(t mockConstructorTestingTNewProductService) *ProductService {
	mock := &ProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
