// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	transaction "ecommerce/features/transaction"

	mock "github.com/stretchr/testify/mock"
)

// TransactionService is an autogenerated mock type for the TransactionService type
type TransactionService struct {
	mock.Mock
}

// CreateTransaction provides a mock function with given fields: token
func (_m *TransactionService) CreateTransaction(token interface{}) (transaction.Core, error) {
	ret := _m.Called(token)

	var r0 transaction.Core
	if rf, ok := ret.Get(0).(func(interface{}) transaction.Core); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(transaction.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTransaction provides a mock function with given fields:
func (_m *TransactionService) UpdateTransaction() (transaction.Core, error) {
	ret := _m.Called()

	var r0 transaction.Core
	if rf, ok := ret.Get(0).(func() transaction.Core); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(transaction.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTransactionService interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionService creates a new instance of TransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionService(t mockConstructorTestingTNewTransactionService) *TransactionService {
	mock := &TransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
